### ISSUE TITLE
Add "no x- headers" rule

### ISSUE THREAD

**Issue by ioggstream** [teamdigitale/api-oas-checker#53]
## I expect

the following rule to be present

```
  no-x-headers:
    description: "All 'HTTP' headers SHOULD NOT include 'X-' headers (https://tools.ietf.org/html/rfc6648)."
    severity: warn
    given: "$..parameters[?(@.in == 'header')].name"
    message: "HTTP headers SHOULD NOT include 'X-' prefix."
    recommended: true
    type: style
    then: 
      function: pattern
      functionOptions:
        notMatch: "/^(x|X)-/"
```

## Instead

it is not

## Note

add a test for this rule
